"""
Mini Healthcare Assistant — Streamlit UI

Flow: user ID -> greeting -> CGM reading -> meal plan -> optional Q&A interrupt.
Uses only synthetic data (data/patients.csv, generated by data/generate_data.py).

Guardrails:
- Identical inputs (same patient + same CGM reading, or the same
  question) are cached via st.cache_data, so re-submitting the same
  values doesn't waste another LLM call — it returns the cached result
  instantly, with just a brief spinner rather than a blocking message.
- Generated results are stored in session_state and always re-rendered,
  so they don't disappear when the script re-runs due to an unrelated
  widget interaction (e.g. typing in the Q&A box).
"""
import os
import subprocess
import time
from pathlib import Path

import streamlit as st

from agents.greeting_agent import load_patients, greet
from agents.cgm_meal_agent import build_meal_plan
from agents.interrupt_agent import answer_question

DATA_PATH = Path(__file__).parent / "data" / "patients.csv"
MIN_SPINNER_SECONDS = 0.6  # keeps the loading indicator visible even on a cache hit

st.set_page_config(page_title="Mini Healthcare Assistant", page_icon="🩺")
st.title("🩺 Mini Healthcare Assistant")
st.caption("Synthetic data only — demo app, not medical advice.")

# Generate the synthetic dataset on first run if it doesn't exist yet.
if not DATA_PATH.exists():
    subprocess.run(["python", str(Path(__file__).parent / "data" / "generate_data.py")], check=True)

df = load_patients(str(DATA_PATH))

if "record" not in st.session_state:
    st.session_state.record = None
if "meal_plan_result" not in st.session_state:
    st.session_state.meal_plan_result = None
if "qa_result" not in st.session_state:
    st.session_state.qa_result = None


@st.cache_data(show_spinner=False, ttl=3600)
def cached_build_meal_plan(first_name: str, dietary_preference: str, medical_condition: str, reading: float) -> str:
    """Cache identical (patient, reading) combinations so re-submitting the
    same values doesn't trigger another LLM call — repeat clicks just
    return the cached result almost instantly."""
    return build_meal_plan(first_name, dietary_preference, medical_condition, reading)


@st.cache_data(show_spinner=False, ttl=3600)
def cached_answer_question(question: str) -> str:
    """Cache identical questions so re-asking the same thing doesn't
    trigger another LLM call."""
    return answer_question(question)


# --- 1. Greeting Agent ---------------------------------------------------
st.subheader("1. Who are you?")
user_id = st.number_input(
    f"Enter your user ID (1–{df['user_id'].max()})", min_value=1, max_value=int(df["user_id"].max()), step=1
)
if st.button("Greet me"):
    ok, result = greet(df, user_id)
    if ok:
        st.session_state.record = result
        st.session_state.meal_plan_result = None  # reset on a new/changed patient
        st.success(
            f"Hi {result['first_name']} {result['last_name']} from {result['city']}! "
            f"Dietary preference: {result['dietary_preference']}. "
            f"Medical condition: {result['medical_condition']}."
        )
    else:
        st.session_state.record = None
        st.error(result)

# --- 2. CGM + Meal Planner Agent -----------------------------------------
if st.session_state.record:
    st.subheader("2. CGM reading & meal plan")
    reading = st.number_input(
        "Enter today's CGM reading (mg/dL)",
        min_value=0,
        max_value=600,
        value=int(st.session_state.record["cgm_reading"]),
    )
    st.info(
        f"📋 On file, your last recorded CGM reading was "
        f"**{st.session_state.record['cgm_reading']} mg/dL**. "
        "If that's still your current reading, you can proceed with it below as-is — "
        "otherwise, edit the value to enter today's actual reading before generating your meal plan."
    )
    if st.button("Generate meal plan"):
        rec = st.session_state.record
        with st.spinner("Checking glucose and building your meal plan..."):
            start = time.time()
            plan = cached_build_meal_plan(
                first_name=rec["first_name"],
                dietary_preference=rec["dietary_preference"],
                medical_condition=rec["medical_condition"],
                reading=reading,
            )
            elapsed = time.time() - start
            if elapsed < MIN_SPINNER_SECONDS:
                time.sleep(MIN_SPINNER_SECONDS - elapsed)
        st.session_state.meal_plan_result = plan

    # Always re-render the last generated plan, so it doesn't vanish when
    # the script re-runs for an unrelated reason (e.g. typing a question below).
    if st.session_state.meal_plan_result:
        st.markdown(st.session_state.meal_plan_result)

    # --- 3. Interrupt (Q&A) Agent ----------------------------------------
    st.subheader("3. Have an unrelated question?")
    question = st.text_input("Ask anything, then come back to your plan above")
    if st.button("Ask") and question.strip():
        with st.spinner("Thinking..."):
            start = time.time()
            answer = cached_answer_question(question)
            elapsed = time.time() - start
            if elapsed < MIN_SPINNER_SECONDS:
                time.sleep(MIN_SPINNER_SECONDS - elapsed)
        st.session_state.qa_result = answer

    if st.session_state.qa_result:
        st.info(st.session_state.qa_result)